---
abstract: 'Access to the CampBX bitcoin trading API'
author:
  - 'Rick Bragg'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Finance-CampBX
requires:
  JSON: 0
  LWP::UserAgent: 0
  strict: 0
  warnings: 0
version: 0.1
